### ISSUE TITLE
quotes don't work around tags

### ISSUE THREAD

**Issue by selfagency** [kellym/smartquotesjs#14]
when my users' code is `"<a href="http://whatever.com">this is my link</a>"` vs.  `<a href="http://whatever.com">"this is my link"</a>` smartquotes doesn't parse properly.

here is an example:

<img width="165" alt="screenshot 2016-03-08 14 37 59" src="https://cloud.githubusercontent.com/assets/2541728/13616163/a619dade-e546-11e5-82e1-15c92b78c464.png">

as you noted on twitter: "looks like it needs to ignore tags when parsing."

**Comment by selfagency** [comment]
you ever get around to fixing this?

**Comment by Permutatrix** [comment]
I hacked together [this thing](https://gist.github.com/Permutatrix/f625ec0a9f902803441a8fe26e9c41c3) a few months ago to use as a bookmarklet, in case that's of any interest to you. It isn't exactly high-quality code, but it's worked for me so far.

**Comment by kellym** [comment]
@selfagency sorry for the lengthy delays on this but if you're still interested, the recent npm / bower versions should resolve your issue.

**Comment by selfagency** [comment]
thanks!
