### ISSUE TITLE
Incorrect open single quote when there's a later apostrophe

### ISSUE THREAD

**Issue by danderozier** [kellym/smartquotesjs#19]
Hello—first, thanks for all your work on this script, it's very useful!

I noticed what appears to be a bug in the latest version (2.0). Here's how to replicate it:

## Original text
```
"If people have a bearded dragon, maybe the neighbors are like, 
'You want me to watch what?'" says Jessica Hagemeier, 
a longtime employee at Cedar Mill's Pet Barn.
```

## Script result
```
“If people have a bearded dragon, maybe the neighbors are like, 
’You want me to watch what?’” says Jessica Hagemeier, a 
longtime employee at Cedar Mill’s Pet Barn.
```

Notice the open single quote before "You want me to watch what?" is an `&rsquo;` instead of a `&lsquo;` as expected. 

However, removing the apostrophe in "Cedar Mill's Pet Barn" resolves the issue:

## Updated text, without apostrophe
```
"If people have a bearded dragon, maybe the neighbors are like, 
'You want me to watch what?'" says Jessica Hagemeier, a 
longtime employee at Cedar Mills Pet Barn.
```

## Correct Result
```
“If people have a bearded dragon, maybe the neighbors are like, 
‘You want me to watch what?’” says Jessica Hagemeier, a 
longtime employee at Cedar Mills Pet Barn.
```

**Comment by kellym** [comment]
Thanks for reporting this. I just pushed up a new version 2.0.1 to npm that should resolve your issues, at least based on this text. If you run into any other issues please let me know!

Thanks!

**Comment by danderozier** [comment]
Thank you!
