### ISSUE TITLE
Bug when there’s an abbreviated year inside a nested quote

### ISSUE THREAD

**Issue by handcoding** [kellym/smartquotesjs#21]
Hi there,

I believe there might be a bug when smartquotes.js is given an abbreviated year inside a nested quote. For instance:

> And then she blurted, "I thought you said, 'I don't like '80s music'?"

That appears to give this result:

> And then she blurted, “I thought you said, ‘I don’t like ‘80s music’?”

And the result that I’d expect is:

> And then she blurted, “I thought you said, ‘I don’t like ’80s music’?”

If you happen to be viewing this issue on GitHub.com, you might be stuck seeing this in San Francisco, which happens to have nearly identical left-single-quote and right-single-quote characters. So if it might help, here’s a screenshot of those test cases but with Helvetica:
	
<img width="683" alt="smartquotes - test case" src="https://cloud.githubusercontent.com/assets/118319/26515058/6ea167d0-423c-11e7-9dda-edb4317519cb.png">

**Comment by kellym** [comment]
Do you happen to know off-hand if this was introduced with the latest patch?

**Comment by handcoding** [comment]
@kellym As it would happen, I only stumbled upon smartquotes.js a few days ago, so I’m not sure whether the latest patch may have had an effect.

**Comment by kellym** [comment]
It looks like it's still happening in the newest version, although slightly different. I'll take a look as soon as I can. Thanks for reporting this!

**Comment by handcoding** [comment]
Anytime!

**Comment by kellym** [comment]
Should be resolved in 2.0.2.
