### ISSUE TITLE
Incorrect text breaking

### ISSUE THREAD

**Issue by thomasdbock** [kellym/smartquotesjs#25]
After your latest fixes, we decided to unleash our best authors and QA on testing our smartquotes.
We did find one extreme case of 'cutting off words'. (and one minor edge case wrong quote)

Cases can be found here:
https://codepen.io/thomasdbock/pen/gWVwGg

example of words being cut off: 
![image](https://cloud.githubusercontent.com/assets/1466381/26623291/8d3ebc92-45ed-11e7-8211-4c9db63722c7.png)

We can see a mix of either words being cut off or incorrect quotes throughout the text.

FYI:
This was an issue before your fixes, but we did find them now, after going back a version of smartquotes, we still see this issue.

**Comment by kellym** [comment]
Just pushed a fix for this, although I wasn't certain about where the edge case of a wrong quote was, and if it could be resolved. If you feel up for testing that branch, that'd be helpful. Otherwise, I'll merge this in later.
