### ISSUE TITLE
Add a hook for custom behavior

### ISSUE THREAD

**Issue by howardjing** [kellym/smartquotesjs#28]
Hi, 

I'd like to add a hook for custom behavior -- so for example

```
smartquotes(element, {
  processString: (string) => (
    string.replace(/\-\-/g, '\u2014')
  );
});
```

to replace double dashes with em dashes. Does that sound fine to you? I'll probably have a PR up today or tomorrow with tests / documentation if yes.

**Comment by kellym** [comment]
You know, a long time ago there was a suggestion of adding behavior for em dashes and ellipses. I was sort of against it at the time, seeing as this is called "smartquotesjs" and I didn't want this library to get bloated with a bunch of other 'smart' conversions. 

However, I'm not certain of many other situations besides quotes, em dashes, and ellipses, and possibly a couple others, and I can't find another js library that handles those, so I'd be willing to revisit that instead. Any other scenarios you were thinking of besides the em dash?

**Comment by howardjing** [comment]
My use case is pretty much just smart quotes and em dashes. I read through #4, and the proposal that they had was to convert double dashes to en dashes and triple dashes to em dashes. On the other hand, I want double dashes to be em dashes, and no en dashes at all. 

Because the conversion process seems ambiguous, I was thinking it might be better to have a processString hook for the user to do their own logic for their own specific use cases at the cost of added complexity to the user.

**Comment by kellym** [comment]
In lieu of this, I've exposed `smartquotes.replacements` as an array of regex/replacement pairs. In order to add the use-case you describe, you should be able to add that like so:

```javascript
const smartquotes = require('smartquotes');
smartquotes.replacements.push([/\-\-/g, '\u2014']);
```
