### ISSUE TITLE
Node.js Port

### ISSUE THREAD

**Issue by kemitchell** [kellym/smartquotesjs#6]
Thanks very much for sharing smartquotes!

I recently pulled the regular expressions out into a [Node.js](http://nodejs.org) module for distribution via [npm](https://npmjs.com), so that I could use the core string-replacement bit in some of my own open source work:

https://github.com/kemitchell/smart-quotes.js

I hope you don't mind that I gave you proper attribution, both in the README and in package.json.

I've watched smartquotes, so I keep my tiny port up to date with progress on your original. I also added you as a contributor to the GitHub repo, just in case.

Thanks,
Kyle

**Comment by callumacrae** [comment]
I don't get it—why didn't you just collaborate with @kellym to restructure this library so that it could be used through npm?

**Comment by kellym** [comment]
I'd agree with @callumacrae, I'd like to add support here to run this server-side as well, so that may remove the need for you to maintain a separate repo just for that. I think @callumacrae is on it :)

**Comment by callumacrae** [comment]
This was resolved in #8 :smile:
