### ISSUE TITLE
minified version doesn't work

### ISSUE THREAD

**Issue by jtlocsei** [kellym/smartquotesjs#9]
Minified version doesn't work, and inserts strange characters instead of quotes. Normal version works fine and I love it. 

Using an online minification tool on the normal version also breaks it and makes it insert strange characters. Must be something about minification that breaks the script.

**Comment by callumacrae** [comment]
I didn't see this. Is it still a problem? I will look into it if it is

**Comment by jtlocsei** [comment]
The bug is still there. Tested with Chrome on a Mac. Happens even in the demo. I edited badger.html to use the minified version of the script and this is what I see:
![image](https://cloud.githubusercontent.com/assets/6704966/10519072/05c2708e-735c-11e5-95ed-31ebd20d61ed.png)

![image](https://cloud.githubusercontent.com/assets/6704966/10519079/140df1cc-735c-11e5-8fa9-df9790431bcb.png)

It's not a big deal because unminified script is only 3KB. But if you're able to fix it then that would be great

**Comment by kellym** [comment]
Definitely need to get that fixed. I'd like to update the handling a bit
and am out of town, but I'll take a look at it this weekend if @callumacrae
doesn't get to it first. Thanks for keeping up with this issue.

**Comment by kemitchell** [comment]
@jtlocsei from your screenshot, it looks like smartquotes is correctly replacing straight quotes with curly quote characters, but the curly quote characters aren't being displayed correctly. I'd guess it's an encoding issue.

Do you have `<meta charset="utf-8">` or `<?xml version="1.0" encoding="UTF-8"?>` in your HTML?

Is the web server serving the minified version with `Content-Type: text/javascript;charset=UTF-8`?

**Comment by jtlocsei** [comment]
@kemitchell you're right, adding <meta charset="utf-8">to the html file fixes it. So, how come the non-minified version works even without adding <meta charset="utf-8"> to the html file?

**Comment by kemitchell** [comment]
Unfortunately, I'd need to use an inspection tool like Chrome Inspector to look at how the browser is interpreting charset on the page, the script file, etc. to figure it out. I suspect it has to do as much with how the server is providing the content to the browser, hence my comments about `Content-Type`.

It sounds like this issue is resolved. Would you mind closing?
